### ISSUE TITLE
Links between scenarioo instances

### ISSUE THREAD

**Issue by zis-meyer** [scenarioo/scenarioo#315]
Some organisations use scenarioo for one application. There, it would be useful to be able to link between these instances.

Stuff to consider for the source system:
- the base URL for the target systems must be configurable in one place (instead of repeating it in each link)
- a step should have more than one link
- there should be a possibility to add some description (e.g., "Button X points to system Y", "Automatic redirect to system Z")

Stuff to consider for the target system:
- the link targets should be stable even if, due to refactoring, the use case and scenario (and maybe even the page) are renamed
- it should be possible to not just link to a scenario, but to a specific step inside a scenario
- the link should still point to something useful if the target no longer exists (due to changes in the requirements)

**Comment by mi-we** [comment]
@bruderol @adiherzog @sascha-kaufmann Might be interesting to talk about this once again. We had a similar issue in the last project, where the application was modularized and thus the UI tests also got split up because every module had its own Scenarioo instance.

**Comment by adiherzog** [comment]
I close this issue because of these reasons:

* It's quite hard to keep test data and "entry point IDs" in sync, so most people would not use the feature
* A feature that is not used by many people is an unnecessary burden for maintenance
* An easier alternative to solve this problem would be writing E2E tests that cover multiple applications (while I would suggest to keep the number of these tests very low).
* We don't have a concrete request from a customer / user of Scenarioo and therefore nobody paying for it.
