### ISSUE TITLE
Show alias target for branch and build aliases

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#353]
Show the target of the branch aliases in the selection list and also in the navigation bar (when a branch is selected).

![branch_alias](https://cloud.githubusercontent.com/assets/3780183/4442101/a7f7a6e2-47db-11e4-8bea-8be4cc4b9481.png)

For builds it is probably useful to show the date in of the aliased build in the navigation bar.

**Comment by adiherzog** [comment]
@Fredericson Did you only implement this for the branch alias or also for the build alias? If I look at the demo (http://54.88.202.24:8080/scenarioo-develop/#/?branch=example-branch&build=most%20recent&tab=usecases) it looks like it's only done for the branch alias.

**Comment by Fredericson** [comment]
@adiherzog no I didn't do anything yet with build aliases. It is also not yet possible to configure a build alias (see issue #237). And the default build alias in the list already refer to the build by date. I see what is missing is the reference to revision by Date in the navigation bar once the build alias is selected. I could fix in a way that the selected alias entry in the navigation bar is consistent with the entry in the list. What was that your idea with build aliases here, what would you like to have? Or did you expect to have the build aliases visible similar as branch aliases but for that we would need to implement first issue #237.

**Comment by adiherzog** [comment]
@Fredericson I do not mean #237, manually defined build aliases have very low priority at the moment. The automatic build aliases (last successful, most recent) should just look the same when they are selected as they look in the dropdown. This means you just have to add the date in brackets and then it's fine. Therefore I reopen this issue. Thanks for changing it.

**Comment by bruderol** [comment]
@adiherzog 
sorry, but I somehow disagree ... builds are different than branches ...
1. to be consistent with branches, what should be displayed in brackets for a build alias is not (only) the build date but the revision number, because that is the main label of the build selection items, and a usual selected build currently does also only display the revision number as label.
2. I think that putting the date in brackets behind the selected label text makes the whole selection box take too much place. Therefore I think we should treat builds different than branches.

Since we do not yet agree on the exact requirements I propose you open a new story for this. Because the core requirement of this story (show target of branch alias in brackets) has been realized.

Therefore I close this story again. Thanks.

**Comment by adiherzog** [comment]
I open it again, because also the build alias is part of this issue. It was always part of the description and title. Let's discuss it here.

In my opinion the important thing that a user wants to see without opening the build dropdown is the date, when the build was created. The user wants to know whether it's a recent or an old build. The revision does not give any information without having access to the VCS. Especially in GIT, where each revision is just a hash code.

Here's my proposal:
* Only use the date without the time in the navigation bar (to save space)
* Also show the revision for the aliases in the dropdown
* Remove the colon after word "Revision" (or maybe even remove the word "Revision"?)

![build alias](https://cloud.githubusercontent.com/assets/3780183/6472082/1e7af682-c1f0-11e4-8c90-d1d631335cc5.PNG)

@bruderol @Fredericson What do you like about this, what would you do differently?

**Comment by Fredericson** [comment]
@adiherzog I think the first Feature you requested is very reasonable. The date is an important information for the user, so the user knows directly how old the build is without klicking on the navigation bar. This gives an advantage to the user. Also if we put only the Date into brackets it will not blow up the navigation bar to much. @bruderol can we have this feature? The other two feature you described, for me they are more optional, more cosmetic with less advantage for the user.

**Comment by adiherzog** [comment]
@Fredericson For me it's also the first feature (the date) that I really want. I don't care so much about the rest. But as it is very easy to do, I suggest to do everything as proposed.

**Comment by Fredericson** [comment]
@adiherzog I implemented it as we discussed. So I close this issue.

**Comment by adiherzog** [comment]
@Fredericson Thanks a lot, looks good.

**Comment by bruderol** [comment]
Sorry, I have not followed this discussion. But I also think that it is (how you defined and implemented it) much better now (because the revision is also visible, where needed). I also think, that the term "Revision" could even be removed, in one earlier comment by @adiherzog 
But for now it is okay, how it is. @Fredericson Thank you a lot!
