### ISSUE TITLE
Deploy documentation of scenarioo-selenium-demo inside a special demo deployment of scenarioo

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#402]

**Comment by bruderol** [comment]
I consider this as obsolete, as we have the simple Pizza example by @adiherzog which is deployed to our demo - we should probably make this our master and decide once on how to proceed with the more complicated demo example.

**Comment by eggerschwiler** [comment]
@bruderol can we close this issue? Or is there something concrete that still needs to be done?

**Comment by adiherzog** [comment]
@bruderol @eggerschwiler I saw that the pizza example is not deployed to the master and develop demos.

I tried to just re-run the CircleCI job of the pizza-delivery project, but that failed (https://circleci.com/gh/scenarioo/pizza-delivery). So I updated some dependencies which made the tests run locally.

Now the build fails on the CI because publishing does not work. It looks like the configured password for the "scenarioo" user is not correct. Do we even have a fixed password on the demo server now or just the randomly generated one?

**Comment by adiherzog** [comment]
@bruderol @eggerschwiler Thought about this a bit more and now I think that deploying through the REST API does not make sense anymore. Should we also deploy the pizza-example like the self-docu (e.g. https://github.com/scenarioo/scenarioo-infrastructure/commit/d5e6fa08b695a1b755db07ce3a586477a0fbdc0c)?

**Comment by eggerschwiler** [comment]
@adiherzog deploying it through scenarioo-infrastructure is the wrong approach in my opinion. Because scenarioo-infrastructure deploys the built scenarioo.war files for each branch together with the self-docu. However, the pizza-example does not have a scenarioo.war.
On the other hand deploying through the rest interface should work. We have a password configured in circleCI which works when we deploy our branches to scenarioo-develop, so it should work here as well. The response I get is a 400 Bad Request and not a 401 Unauthorized. In the Tomcat log I can see that the request was sent to the correct rest endpoint. The problem seems to be with the zip file that we are uploading. I'll try to further analyze and solve this problem.

**Comment by eggerschwiler** [comment]
I downloaded the generated e2eScenariooDocu.zip and tried to upload it to a local Scenarioo instance. I received the same 400 error. In the local server log I found the following entry
`DEBUG InvocableHandlerMethod        : Failed to resolve argument 0 of type 'org.springframework.web.multipart.MultipartFile'
org.springframework.web.multipart.support.MissingServletRequestPartException: Required request part 'file' is not present`
The strange thing is, if I use a zip-file from a scenarioo branch then the same command works.

**Comment by adiherzog** [comment]
@eggerschwiler Thanks for analyzing this. I think the file size is not the problem. Maybe it's related to how the Spring endpoint is configured, others seem to have similar problems: https://stackoverflow.com/questions/46563182/spring-file-upload-required-request-part-is-not-present?rq=1

**Comment by eggerschwiler** [comment]
@adiherzog pizza-delivery example is now present on both scenarioo-develop and scenarioo-master. Can we close this issue now?

**Comment by adiherzog** [comment]
@eggerschwiler Yes, we can close it. Thanks a lot for fixing the bug and making a hotfix release!
