### ISSUE TITLE
Deploy Scenarioo self-documentation after build

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#404]
The e2e tests should generate scenarioo documentation output and deploy it instantly, so that it can be browsed on our CI after each commit.

Precondition: #167

**Comment by adiherzog** [comment]
This works now. The self-documentation is deployed to the Scenarioo instance it belongs to. E.g. the develop branch documentation is deployed here: http://54.88.202.24/scenarioo-develop/#/?branch=develop&build=last%20successful&tab=usecases

**Comment by bruderol** [comment]
As allready mentioned by email: I think the name of the branch in the documentation should be renamed to something meaningful like "scenarioo-self-docu" instead of "develop". the branch of the scenarioo branch to view is given by the URL of the scenarioo webapp allready (one scenarioo installation per branch).
