### ISSUE TITLE
AngularJS Styleguide adaptions

### ISSUE THREAD

**Issue by xeronimus** [scenarioo/scenarioo#408]
After the introduction to the AngularJS Styleguide, we need to discuss and decide which of the presented conventions we want to adopt for the scenarioo webclient.

Afterwards, we can adapt our code-base to match these conventions.

**Comment by bruderol** [comment]
@adiherzog @xeronimus 
I think we should mention the new controller structure and the most important points from the styleguide, that we discussed and agreed on, in our developer guidelines.

I started to document this here:
https://github.com/scenarioo/scenarioo/wiki/Coding-guidelines

You can precise it, if I missed something important. Thank you.

@adiherzog Can you please also open new issues for other controllers or components that we need to refactor according to the styleguide? And also for things like using Resolvers for loading data before page gets displayed and for general error handling, if not yet present on the issues. Then I think we can close this issue here. Or what you think? 
Thank you.

**Comment by bruderol** [comment]
@adiherzog I still wait for an answer regarding the following: Can we close this? Can we open new issues for concrete follow up tasks?

**Comment by adiherzog** [comment]
I created the following new issues:

* #417
* #418

If you think we should do more, feel free to add more issues.
