### ISSUE TITLE
Support multiple languages in screenshots

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#445]
Some users (e.g. @patrickschweizer) want to execute UI tests in multiple languages and want to switch between the various languages of a screen.

**Comment by bruderol** [comment]
I see this in project of @patrickschweizer, works quite well with using different branch for different language.

I not see urgent need to have extension for this.

But something more interessting could something like a device type be (because this might have more impact than changing the language, e.g. special scenarios for some devices).

**Comment by bruderol** [comment]
See #460, which will solve this issue in a more elegant and generic way, I will close this issue therefore.
