### ISSUE TITLE
Configure comparable builds

### ISSUE THREAD

**Issue by magitnu** [scenarioo/scenarioo#484]
As an administrator, I want to configure a list of comparison Builds, so that on an import of a base build a comparison is executed for each configured comparison build. 
Such a configuration is called comparison alias and consists of a base branch name, a comparison branch, a comparison build and a comparison name. The Comparison name will be displayed to the user in the comparison selection menu. For further information have a look at the "choose comparison build" user story https://github.com/scenarioo/scenarioo/issues/504.

**Acceptance criterias:**
-	It is possible to configure the comparison aliases in the xml config file
-	It is possible to define a comparison name to each comparison build

**Testcases:**
-	comparisonName="Comparison to Version 1.0", baseBranch="develop", comparisonBranch="release-1.0", comparisonBuild="build-10-03-2016” ==> this will trigger on every new build in branch "develop" such a comparison. The diff info will be save under /scenarioo-application-data/diffViewer/develop/build-28-04-2016/Comparison to Version 1.0
-	comparisonName="Comparison last Sprint", baseBranch="develop", comparisonBranch="develop", comparisonBuild="build-10-03-2016” ==> this will trigger on every new build in branch "develop" such a comparison. The diff info will be save under /scenarioo-application-data/diffViewer/develop/build-28-04-2016/Comparison last Sprint

**Comment by bruderol** [comment]
See my more detailed email about this issue here to you. Please provide more detailed information here on how this will be solved, e.g. how the configuration would look like, what test cases as concrete examples are covered and also I think we might have to rethink or better define the wording / glosar / domain model for this whole project. E.g. I think that "comparable build" is not the right wording, that is intuitive for users. I would rather say, that the admin configures a "Comparison" to be calculated for a newly imported build on a branch and compare it with an existing build on another branch or even the same branch.

**Comment by Dogen91** [comment]
added comparisonAliases to the configuration object. also implemented functionality to write and read xml config.

example xml snippet:
![config](https://cloud.githubusercontent.com/assets/5638334/14883756/4f14ceac-0d40-11e6-9f2f-0631e4185b0e.PNG)

**Comment by bruderol** [comment]
@Dogen91 I only see your last comment now. 
Question: Is there a reason why this is named "Alias"?? I not think that "Alias" is a good name for configuring a comparison (which is much much more than just an alias, as e.g. a branch alias is). I think it is very confusing to use "alias" in the names for comparison configurations too. this is a totaly different concept.

**Comment by Dogen91** [comment]
I disscussed it today with @magitnu and in our opinion comparison alias is an appropriate name for that. I see the point, that the alias itself is only the comparison name. But in our case it stands for the whole configuration. So if we are talking about the "exampleComparison" from the example above then we are talking about the whole configuration. So the comparison alias is not just a pseudonym for the comparison build, it stands for the configuration including branches and builds.

I had to extend the conifugration object with the comparison aliases. Therefore i wrote "also implemented functionality to write and read xml config". We are using the existing functionality.

**Comment by bruderol** [comment]
" So the comparison alias is not just a pseudonym for the comparison build, it stands for the configuration including branches and builds." ... YES, exactly, and that is why I thik the word "alias" does not fit here at all! See my proposal that I once sent for the configuration by email:

<comparisonConfigurations>
                <comparisonConfiguration>
                               <name>Comparison to Version 1.0</name>
                               <comparisonBranch>develop</comparisonBranch>
                               <baseBranch>release-1.0</baseBranch>
                               <baseBuild>last successful</baseBuild>
                </comparisonConfiguration>
                <comparisonConfiguration>
                               // please extract more of this elements from textual examples above to test all the 5-6 given key examples!
                </comparisonConfiguration>
</comparisonConfiguration>

Please avoid to use the word "alias"in comparisons, because it means something conceptually different in Scenarioo (for branches and builds). 

And by the way: If the comparisonConfiguraiton is missing diff viewer is considered to be turned off (feature toggle).
