### ISSUE TITLE
Screenshot comparison

### ISSUE THREAD

**Issue by magitnu** [scenarioo/scenarioo#490]
As a user, I want a comparison between the screenshot of the base build and the screenshot of the comparison build, so that I can easily detect changes between these two screenshots.

**Acceptance criterias**
Server
1.Different sized screenshots can be compared
2. A DiffScreenshot, which marks the differences between these two screenshots in a specific color, is generated
3. The DiffScreenshot will be saved only, if differences occur.
4. The Difference between these two screenshots is declared in percent
5. The step view contains a new tab to compare these two screenshots
6. If the required software suite for image comparison is not installed, scenarioo can be used without the screenshot comparison feature

Client
1. The user can show/hide the DiffScreenshot whit a toggle button
2. The toggle button status is saved even during a refresh

**Testcases**

1. Screenshot A equals Screenshot B ==> No DiffScreenshot is saved. Difference is 0%.
2. Screenshot A unequal to Screenshot B ==> DiffScreenshot is saved. Difference is between 0% and 100%.
3. Screenshot A size is different than the size of Screenshot B ==> DiffScreenshot is saved. Difference is between 0% and 100%.
4. GraphicsMagick is not found or not installed ==> No exception is thrown, just a log entry. Difference is set to 0%. So that the DiffViewer still can display stuctural changes.

Software suite for image comparison
http://www.graphicsmagick.org/

Java Interface for graphicsmagick
http://im4java.sourceforge.net/

Sample screenshots
[screenshota](https://cloud.githubusercontent.com/assets/11535440/14602377/d9d3fbfc-0567-11e6-9966-d49958b24288.png)
[screenshotb](https://cloud.githubusercontent.com/assets/11535440/14602378/d9d4d09a-0567-11e6-8e66-38730c7c3755.png)
[diffscreenshot](https://cloud.githubusercontent.com/assets/11535440/14602303/7ae772e0-0567-11e6-810e-d6ce20f003db.png)

**Comment by bruderol** [comment]
"The DiffScreenshot is only saved, if no differences occur." - realy? :dizzy_face:

**Comment by magitnu** [comment]
If there is no difference between two Screenshots, there is no need for a DiffScreenshot.
Because there would be no additional information on it.
Therefore I thought that we could save a lot of disk space, if we delete such a DiffScreenshot.
And I guess most of the Screenshots are equal to each other.

I heard some Builds are up to 6 Gigabyte large and have thousands of Screenshots.
I belive it is even planned to reduce the amount of data by switching from xml to json.
So why not reduce the need of storage space by deleting this DiffScreenshots.

It's up to you if you want to keep all of the DiffScreenshots. From the technical side of view, it would be easier to keep all the DiffScreenshots.

**Comment by bruderol** [comment]
@magitnu yes, of course, I perfectly understand, but I just think the sentence that I mentioned is somehow wrong - please read again - sorry, if that was not clear, I thought it is obvious. you see it now?? :smile:

**Comment by magitnu** [comment]
@bruderol Now I get it :) Because of the puzzled smiley I thought you totally disagree with the point, so I did not read it in detail.

**Comment by bruderol** [comment]
ok, sorry - I was in a hurry. But I appreciate how you detail the stories before implementing them. That is great! Top! :+1: Thanks a lot! Great to see that you make very good progress.

**Comment by magitnu** [comment]
Implemented Screenshot comparison
![image](https://cloud.githubusercontent.com/assets/11535440/14940857/f7327010-0f86-11e6-8275-fab1923b7120.png)

**Comment by magitnu** [comment]
@bruderol 
As discussed after the usability test we will add more functionality to this user story.
 - Add additional view: Single-page-View (in the same tab)
 - Add Buttons to switch between single-page-view and side-by-side view
 - Create button bar on top of the screenshots. Buttons: [Button Design](https://cloud.githubusercontent.com/assets/11535440/15507565/7867cc28-21cc-11e6-95c0-0e8392ec3429.jpg)

 - Highlight the changes in the baseScreenshot instead of the comparisonScreenshot

I already tested the screenshot comparison. The screenshots are confidential, therefore I will send you the result by mail.

**Comment by magitnu** [comment]
@bruderol 
Screenshots of the new features
Side by side view
![sidebyside](https://cloud.githubusercontent.com/assets/11535440/15805276/55c90ed6-2b25-11e6-8319-83de670e7ed1.PNG)

Single page view
![singlepageview](https://cloud.githubusercontent.com/assets/11535440/15805277/55dc802e-2b25-11e6-95f8-17f43111671a.PNG)

**Comment by bruderol** [comment]
something seems to be wrong on the demo (maybe a bug?):
Following screen in my oppinion should have changes:
http://demo.scenarioo.org/scenarioo-fork-diffviewer/#/step/Donate/find_donate_page/donate.jsp/0/0?branch=wikipedia-docu-example&build=2014-03-19&comparison=To%20Projectstart

Furthermore I still think, that the changes should be highlighted in the screenshots in yellow color, as this is the color for changes everywhere else (and red means removals, but here we can not decide whether it is a removal or addition, therefore yellow would be the right color).

Furthermore the naming is not understandale for users. What does "base screenshot" mean and what "comparison". Which one is the old one, which the new one? Maybe use "current screenshot" and "previous screenshot" or something similar.

The rest looks much better than before, I like the navigation buttons. Thanks a lot! :+1:

**Comment by magitnu** [comment]
thanks for your feedback:

On the demo server the comparison data is not correct. It was generated before a bug was fixed in [this commit](https://github.com/magitnu/scenarioo/commit/88a54e89fe343f501b0e2804ef8dcbdbdfa4d6a5). You need to delete the DiffData and make a reimport to get the correct data.

You are right, yellow/orange means something has changed. But the contrast is not very good with these colors. See this screenshot as example:
<img width="210" alt="highlightcolors" src="https://cloud.githubusercontent.com/assets/11535440/15817704/96e08d7c-2bd9-11e6-89fc-dc81848efd3e.png">
I suggest to mark changes in red.  In an upcomig version, which might include a configuration view, it is no big deal to add a field to choose the color, so that the user can choose the color himself. Because it is only one parameter on the graphicsmagick call.

We already had some thoughts about the naming in the frontend. Not only is it possible to compare to old builds, but also the comparison to newer builds is possible. Thats why "previous screenshot" is not always right. But we can change "base screenshot" to "current screenshot". It should be more clear for the user. The only drawback is the difference to the [glossary](https://github.com/magitnu/scenarioo/blob/develop/documentation/diff-viewer/glossary.md)

**Comment by bruderol** [comment]
I like the orange, I hate the red, because it suggests that it is something that has been removed (as in other places where red is used, but this is not the case here). There is no color that will be best in any case, but the orange or even the yellow one seems quite okay to me.

Also red is not optimal, because often used in UIs for validation messages.

Configuration of the color would be cool, but still we should provide a consistent default color (I mean consistent with other colors used, so I would prefer the same yello/orange as for other changes).

And no, you can not really compare to newer builds, because when a build is imported (and thus the comparison is calculated), there is no new build yet to use to compare with. the imported one (and thus the base one, according to your glosary), is usually allways the newest one. Or am I wrong?

But maybe something like "current" and "compared to" looks like a good naming to me (at least better to the one defined in the glosary, that nobody understands, maybe we should have reviewed and thought about the glosary better, sorry for that).

**Comment by magitnu** [comment]
Then I set orange as the default color. Because in orange, changed text is quite readable. 

I will also change the button and screenshot label as you recommended.

It is a corner case, but it is possible to compare to new builds. When you reimport a build, then the comparison gets recalculated. In this case new builds are available for comparison.

**Comment by bruderol** [comment]
that looks AWESOME! :smile: :+1: 

I only have some final input concerning the text over the screenshots (I thought hard about this):

* I think it would help to also show the timestamp (date field of the build)
* and also the build name (which should be the display text to use for a build anyway, same as in build selection box on develop branch, the revision is an optional field, and is also helpful to display if set)
* So my proposal would be to display:
    * for current version: "Current: [{{build.aliasName}} - ] {{build.name}} ({{build.date}} [ - {{buid.revision}}])" 
    * for compared version: "{{comparison.name}}: {{build.name}} ({{build.date}}[ {build.revision}}])" 
* An example:
    * Current: last successful - build_312 (2016-06-13 14:23 1.0.F998FDE)
    * To Projectstart: build_1 (2014-03-23 12:03 1.2.F389AD3)
* [] means only if the contained fields are not empty
* Then we should add a text behind the text for current screenshot in the highlight color, saying: "highlighted changes" (as kind of a color legend) that is only displayed if the screenshot with highlighted changes is displayed.

Most of this proposal is consistent with what we allready have as display text for builds in the build selection box anyway, but it seems to me, that you have merged some changes wrongly on your current fork, because on the develop branch, the build selection box has allready since long time been changed to display the build texts differently, as you can see here: http://demo.scenarioo.org/scenarioo-develop
Maybe there have some changes been wrongly merged to your fork?
Please take care to at least correct this last point. Thank you.

**Comment by magitnu** [comment]
Screenshot of the new screenshot texts:
![stepcomparison](https://cloud.githubusercontent.com/assets/11535440/16115234/1314c932-33c6-11e6-9a22-68f66c3f3801.PNG)
We could also fix the Issue with the different display texts

**Comment by bruderol** [comment]
:+1: great, I like it!

I think we should now just resolve the issue with the test data on the demo, for we have some screens with real changes, for example here:
http://demo.scenarioo.org/scenarioo-fork-diffviewer/#/step/Donate/find_donate_page/donate.jsp/0/0?branch=wikipedia-docu-example&build=last%20successful&comparison=To%20Projectstart

what would we have to do, that this get calculated correctly? I think this should be recalculated on the CI/Demo Server after each new deployment!

And I like the name of your comparison "To last Sprint", could we also put that into the demo config. Because "To Projectstart" makes less sense.

Thanks a lot!

**Comment by bruderol** [comment]
@magitnu 
I tried to remove the existing data on the demo server to get it recalculated - but still I see now changes here (0%): http://demo.scenarioo.org/scenarioo-fork-diffviewer/#/step/Donate/find_donate_page/donate.jsp/0/0?branch=wikipedia-docu-example&build=last%20successful&comparison=To%20Projectstart
