### ISSUE TITLE
Disable Diff Feature

### ISSUE THREAD

**Issue by magitnu** [scenarioo/scenarioo#523]
As a user, I want to disable the Diff Viewer feature, so that no additional diff information is displayed.

Acceptance criterias:
- The User can select 'none' in the comparison selection menu
- If 'none' is selected, no diff information data is getting displayed or loaded
- The Browser should remember the selection of 'none'. So that it is preselected even if the user reloads his session (like in #504) 

Testcases:
- 'none' get selected ==> diff information data is hidden
- another comparison get selected ==> diff information data is shown
- 'none' is selected, browser reloads ==> 'none' is still selected

**Comment by Dogen91** [comment]
Implemented another finding from the usability test. Renamed Comparison: none to Comparison: Disabled (Available x).
Another problem at the usability test was that the test persons didn't find the comparison menu well at the first time. So we decided to change the font color from gray to white so that it is more present. if you dont like it we can easyli revert this change.
![disabled](https://cloud.githubusercontent.com/assets/5638334/15646799/16a92868-2660-11e6-95b2-0b0cd619f911.PNG)

**Comment by bruderol** [comment]
:+1: Thank you!

**Comment by bruderol** [comment]
one feedback: the item in the drop down to turn it off again should simply read "Disable" or "None" (without the number of available comparisons) and should only be visible, if a comparison is currently selected.

**Comment by Dogen91** [comment]
Renamed menu item to "Disable" and made it only visible if a comparison is currently selected.

**Comment by bruderol** [comment]
:+1:
