### ISSUE TITLE
Don't show "Use Case:" in scenario if use case description is empty

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#532]
![empty_uc_description](https://cloud.githubusercontent.com/assets/3780183/15213952/8165d760-184a-11e6-84c4-777ac592b59f.PNG)

**Comment by bruderol** [comment]
:+1: 
we should rethink about styling of the title block.

**Comment by adiherzog** [comment]
Yes, maybe we can move the description of the use case and the scenario into the details panel on the right.

**Comment by bruderol** [comment]
Of course we can. good idea.

**Comment by adiherzog** [comment]
I moved the descriptions to the details box. @bruderol Could you please have a look? Is that ok, or do you have ideas for improving it further?

**Comment by bruderol** [comment]
I had a look at it, and Iike it :+1: 
Thanks a lot!

Just some ideas or thoughts for improvements:
1. Also in the step view we should provide same context information about current selected use case and scenario.
2. Since only the usecase name together with the scenario name provide the real identifier of inside which context (=scenario) I am, and this would be often useful for the user to (1) see it in a short form at a glance and (2) be able to copy and paste it for some emails, reports, etc. (in my current project I had exactly this issue today, when analysing some failing tests and to write a short report about it ... I wanted to copy and paste from one location the readable identifier of the scenario as a one liner, to paste it to a failure report in a readable form). That is why I addtionaly propose the following: display in someplace the usecase name just followed by the scenario name as the "full scenario name" (detailed design needs to be done for that of course).
