### ISSUE TITLE
Option to exclude HTML sources in full text search

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#553]
Leftover of #18

Currently there is no possibility to search everything except the HTML sources.

Design:
- either a simple flag for html sources
- or: a configurable list of fields to exclude from search

**Comment by bruderol** [comment]
no wrieframe needed, just config through XML.

**Comment by bruderol** [comment]
i will try to implement it for Reelase 2.3

**Comment by bruderol** [comment]
I remove myself as an assignee, since @featureenvy allready implemented - his solution does even make it configurable through a checkbox for each search.

Still to do:
- remember user's last decission (search HTML or not?)
- put this additional search flags into a special search options dropdown for not occupying more space in header (later there might be more options in this popup, e.g. whether to search page text, metadata, etc.)

**Comment by bruderol** [comment]
@adiherzog What do we do with the current implemented solution? maybe we have to adjust slightly?

**Comment by adiherzog** [comment]
@bruderol @featureenvy Just discussed with Rolf to move the checkbox to the results page so that we save some space on the Navigation bar and have a cleaner UI. Will work on this after merging the PR.

**Comment by adiherzog** [comment]
I moved the checkbox to the search results page and the state is now stored in local storage.

**Comment by bruderol** [comment]
👍 😃 Thanks a lot! 🍻
