### ISSUE TITLE
Adjust Step Comparison View

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#603]
The Step Comparison View needs to be reviewed and slightly improved after latest changes to the comparisons.

Acceptance criterias
* order and logic of behaviour of buttons makes sense and is understandable to the user (to be reviewed by Rolf and some other users)
     * also check that it is understandable, in case there are no changes at all or one of the screenshots is just missing (added or removed step)
* the labels above the screenshots needs to be improved: currently it is not easily understandable in all cases which screenshot shows which version and it is also not very consistent what is displayed
    * the label displayed should correspond to the text that is displayed in the dropdown selection more or less
    * displaying a branch or build alias might not make much sense here
    * keyword "Current" might make sense to additionaly mark which screenshot is the current selected build
    * it should not depend on what is displayed whether the comparison build was configured using an alias, in any case the concrete used build/branch label should be visible
* the URL of the view should as well contain the selected tab, such that a link to the comparison view can be sent by link.

This story might need clarification with @bruderol on some detail design by reviewing the current situation.

**Comment by adiherzog** [comment]
With the diff viewer feature there are now many layers of menus, tabs and buttons on the step view. I started making some improvements:

* Breadcrumbs are now right below the navigation bar. This makes the screen look a bit calmer and saves some vertical pixels.
* Rephrased "Substep 1 of 3 on current page" to "Step 1 of 3 on Page" (shorter) and included it in the step navigation. As this text sometimes led to a line break, this saves some space. It also simplifies the UI.
* Moved the "Show Highlights" button all the way to the right, so that it does not jump around when switching to the single page view.
* Removed the text "highlighted changes", as this should already be clear by the state of the "Hide Highlights" button.

This is not checked in yet. @bruderol @danielsuter How do you like it? Any more ideas how we can simplify the UI, gain space or make it better understandable?

At the moment:
![image](https://user-images.githubusercontent.com/3780183/28932012-59fc6f92-7878-11e7-9764-88b7ebd96f2b.png)

New:

![image](https://user-images.githubusercontent.com/3780183/28932039-6fa38092-7878-11e7-967c-b34eefeab081.png)

**Comment by adiherzog** [comment]
I commited it. We have to further improve the main navigation bar, because with the comparison dropdown and the search field shown, it results in two rows, which looks quite ugly.

**Comment by bruderol** [comment]
@adiherzog Thank you! I like the new header a lot - what I think is missing is the inidcator that you removed about the color of changes (legend) when they are highlighted.

**Comment by bruderol** [comment]
Bug to be fixed: if highlights are turned off, the right side screenshot is bigger than the left one. 

![image](https://user-images.githubusercontent.com/755721/30590834-9769397c-9d40-11e7-9edd-9b24db81c20e.png)

**Comment by bruderol** [comment]
i improved the button bar to control the diff viewer comparison view:
![image](https://user-images.githubusercontent.com/755721/31234333-ecc2194c-a9ee-11e7-8ad1-dd7a38e6bc48.png)

as discussed with @adiherzog - also again displaying the legend text "Highlighted Changes in Screen" in configured color of image highlights.

**Comment by bruderol** [comment]
needs some reork: somehow the labels over the screen seem to got lost somehow :-(

**Comment by bruderol** [comment]
I close this - new bug introduced by migration to webpack will be covered in separate issue #657
