### ISSUE TITLE
Image Difference Comparison Algorithm

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#615]
At the moment the comparison algorithm for images returns some unexpected results: when I compare a 100% white image with a 100% black image of the same size, I would expect a difference of 100%, but instead I get 86.60254037844386. @til77 Is this intentional? Would you mind if we changed this?

@bruderol We need to decide whether we want to count a pixel as 100% different as soon as it's value is not exactly the same or whether we want to allow for gradual differences per pixel like it is implemented now. I would propose that a pixel is 100% the same if the RGB value is 100% the same and otherwise it's totally different. Probably there will be slight rendering differences, so we need a small threshold.

See also ignored tests in `ScreenshotComparatorTest.java`.

**Comment by til77** [comment]
Feel free to change the algorithm. You can probably change `ScreenshotComparator#calculateAbsoluteError`  to divide by three instead of four in line ~164. We implemented the algorithm to match the MAE algorithm of ImageMagick but a result of 100% for a totally different image probably matches the expectations of users more and the alpha layer is not of importance for screenshots anyway.

**Comment by bruderol** [comment]
@til77 thanks a lot for the feedback! 

We will slightly adjust the calculation then, but keep for now most as it is now.

I propose to divide by 3 instead of 4 and keep the rest for now, as it is. 

Later it might be as well a good idea to have a threshold and a configuration for it - but for now I think we are good enough to use the same claculation that ImageMagick was using for difference calculation, which has the advantage that only small color changes will not count as highly weighted as big differences in colors do, I see that as a good solution how it is currently implemented. Would not change that unless anybody complains.

Conclusion: I will change the division factor and then close this issue. Ok?

**Comment by bruderol** [comment]
Did it. 
@adiherzog Can you review my changes in commit above?
I think it is okay now. Special thanks for the great unit test that is great to udnerstand what it does and why (see my explanations now in the comments of the test)!
👍 

Can we close this?

**Comment by adiherzog** [comment]
@bruderol Reviewed it and it looks fine to me. Thanks for the comments in the unit tests too. I'm going to close this issue.
