### ISSUE TITLE
Hello all, for a beginner with selenium i can't really understand the tutorial or the documentation!  

### ISSUE THREAD

**Issue by Suhilaa** [scenarioo/scenarioo#642]

**Comment by bruderol** [comment]
Hi Suhilaa,

Thanks for the feedback. But please provide some more precise descriptions which parts of the tutorial you not understand and why. Otherwise we can not improve it.

Also I have to say: Scenarioo's main target is not to help beginners with Selenium. Scenarioo does work with any kind of testing toolkit and is more an addon for advanced automated testers.

I will close the issue for now, but we can reopen it as soon as you can tell us more precisely what we should improve. 

Thanks.
