### ISSUE TITLE
Can't debug E2E tests using node 8.10

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#676]
When using the `browser.pause()` statement to debug a protractor test using node 8.10, I get this error:

```
module.js:549
    throw err;
    ^

Error: Cannot find module '_debugger'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Code\scenarioo\scenarioo-client\node_modules\protractor\built\debugger\debuggerCommons.js:1:82)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

The reason for this is that protractor does not support this kind of debugging anymore in node 8.x. See also: https://github.com/angular/protractor/issues/4307

On the build server we still have node 6.11.5, so it's not a problem there.

I will locally downgrade node to the same version for now, but we should soon upgrade to the latest LTS version (8.x).

Acceptance Criteria:

* CI upgraded to latest LTS version of node
* Team informed to upgrade their node to latest LTS version
* CI upgrade to latest LTS version of node
* Debugging of E2E tests works in some way (new approach without control flow)
* The documentation regarding debugging is updated: https://github.com/scenarioo/scenarioo/blob/develop/docs/contribute/e2eTesting.md

**Comment by bruderol** [comment]
I put it to next release - not realy relevant for this release

**Comment by adiherzog** [comment]
One reason we want to update to node 8.x is that in node 6.x the package-lock.json file is not written yet. Just discussed it with @bruderol and we decided to upgrade to node 8.11.1 LTS.

**Comment by bruderol** [comment]
Thanks for the links - I think the removal of the control flow is bad - While I like the new possibilities of await of course, I think the new way of writing protractor tests with awaits is very very VERY error prone!!! because: if you forget one await it will not be guaranteed in what order the commands are executed and you will get unstable tests.

this situation is unacceptable to me and we will have to find a way how we can mitigate that problem or whether we should maybe just use a real synchronous test api then - because: what is all this asynch API worth anyway if we then have to write an await before each API call, that is just bad!!! I am disappointed of protractor they do not provide a better answer to that, as far as I can see - or did I miss something???

**Comment by bruderol** [comment]
I wouldnt call it a hack. Just becasue something has some asynch complexity it does not necessarily mean it is a hack. Now without the guarantee of order anymore- I think it has become even more hacky.

**Comment by bruderol** [comment]
@adiherzog Is this still an issue or can we close??

**Comment by adiherzog** [comment]
I just updated the documentation and will close the issue.
