### ISSUE TITLE
Scenarioo Selfdocu: Compare master and develop - deploy them to same demo

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#720]
I noticed that master is not deployed in our develop demo. Therefore the comparison with master does not work. See failed imports in Comparison tab: http://demo.scenarioo.org/scenarioo-develop/#/manage?branch=scenarioo-develop&build=last%20successful&comparison=Disabled&tab=comparisons

@bruderol Will the master documentation be deployed to develop after the release? If not, should it be?

**Comment by bruderol** [comment]
Yes, i knew that this is not going to work when I configured it. I think we should maybe deploy both `develop` and `master` docu to both the master demo as well as to the develop demo.

**Comment by bruderol** [comment]
Ok, I adjusted it - now develop and master are always deployed to both major demos. So that it should be available on both for demo purposes.

**Comment by bruderol** [comment]
done, see #721 - also see my thoughts about it and why I deployed to both master and develop

**Comment by bruderol** [comment]
@adiherzog please review and merge. Thanks.

**Comment by bruderol** [comment]
it happened again:
http://54.88.202.24/jenkins/job/scenarioo/job/feature%252F720-deploy-selfdocu-for-master-and-develop-to-both-demo-instances/3/

Out of Memory in Comparisons!

**Comment by bruderol** [comment]
@adiherzog I'll reopen this - because of a comment by you somewhere on the merged PRs that you think we should copy one master docu to develop to have the comparison once before we release.
I think this is a valuable point!

BUT - Problem here:
We can not just copy the latest master Outcome ... unfortunately .... because it uses totaly different naming for pages in scenarioo reports --> would result in 100% differences again, prety useless.

We have 3 Options how to proceed:

1. Option:
- Adjust the master branch to caclulate page names the same that the develop branch currently does.
- Run e2e tests on master again
- Hope and pray that the tests still run on master branch
REMARK: I wouldnt be surprised if that does not work easily anymore, because of many changes we did, like: different NPM version, elasticsearch 2 gone, and and and ...

2. Option: find a way how to correct page names in existing master scenarioo docu (not sure, whether that would be feasible at all)

3. Option: Not do anything, wait for the release to happen and make sure that we not run into same situation on next release again (so we should ensure that we keep the structure how we generate our documentation form now on more or less!!)

@adiherzog What do you think? 
My oppinion: I do not have time to make this work until the release, sorry. Therefore I vote for Option 3.

**Comment by adiherzog** [comment]
@bruderol That's fine with me, let's go for option 3 then.

**Comment by bruderol** [comment]
@mi-we I added this to the release milestone for next release to ensure we have comparisons to latest release finaly available after next release again in master and develop demo. W ehave to prepare this before the release for it to work after the release again.

This will need some work because new CI & infrastructure does not publish self docu anymore to both master and develop demo anymore for develop and master branch. to be solved. Also we should enforce the comparison in config, if not yet.

**Comment by eggerschwiler** [comment]
I've been trying to include an additional step to upload the develop docu to scenarioo-master, however, I'm struggling with the correct way to only execute this step for the develop branch.

The other direction should already work. If master branch is built it will be uploaded to scenarioo-develop like all other branches. The comparison configuration from develop to scenario-master (last successful) is already present on scenarioo-develop.

So unless, I have missed something only the deployment of develop to scenarioo-master with the corresponding configurations is missing.

**Comment by eggerschwiler** [comment]
I believe this issue is ready for the release.

We have two different requirements, first deploy master self docu to develop, second deploy develop self docu to master.

1.) Deploy master self docu to develop
This is already part of the circleci config.yml that is checked in on develop. Because for every branch (that includes master in the future) that is built the self docu is uploaded to develop.

2.) Deploy develop self docu to master
For this the new job publish_selfdocu_to_master was added. It will only be triggered for the develop branch and it downloads the latest artifact and uploads it to scenarioo-master. This is implemented on the branch "feature/720-publish-develop-to-master". 
@bruderol: Am I correct in the assumption, that this can only be activated after the release and after master has the new version of Scenarioo? If that is the case, then we should either wait with merging this branch back to develop till after the release, or we merge it but disable the actual upload, so that develop builds will not fail.

**Comment by bruderol** [comment]
@eggerschwiler thanks, it's perfect!
