### ISSUE TITLE
REST service to upload builds fails for small zip-files

### ISSUE THREAD

**Issue by eggerschwiler** [scenarioo/scenarioo#934]
When trying to upload a small zip file with the pizza-delivery example to develop, the upload failed.
While trying to reproduce the rest upload locally on Windows to a Spring Boot deployed Scenarioo Application, the upload failed for small and large files (with different errors).
Finally, after the upload was fixed, deleting the temporary working directory failed on Windows.

For more details see issue #402

**Comment by adiherzog** [comment]
Thanks a lot @eggerschwiler for fixing this so quickly!

I think this bug is quite severe for people who rely on the REST endpoint for documentation upload. Therefore we should probably release a new version of Scenarioo soon.

Furthermore we should cover this endpoint with an automated test.

@bruderol What's your opinion on this?

**Comment by eggerschwiler** [comment]
@adiherzog I added an integration test that verifies that the REST upload works. I met with @bruderol yesterday, and we agreed that we will do a bugfix release. I'll try to get it done this week.
